// Generated by scripts/build.py from design/04-couples-pathways.html; do not edit.
const config = {
      darkMode: "class",
      theme: {
        extend: {
          colors: {
            "primary": "#0F172A",
            "secondary": "#C26D4D",
            "secondary-light": "#FAEDE8",
            "secondary-dark": "#94492C",
            "surface": "#F9F9F7",
            "surface-low": "#F4F4F1",
            "surface-card": "#FFFFFF",
            "surface-tint": "#EFEFEA",
            "on-surface": "#1A1C1E",
            "on-surface-variant": "#585D63",
            "outline-soft": "#E4E4DE",
            "terracotta-warm": "#FAF2ED"
          },
          fontFamily: {
            "display": ["Playfair Display", "Georgia", "serif"],
            "body": ["Plus Jakarta Sans", "-apple-system", "sans-serif"],
            "inter": ["Inter", "sans-serif"]
          }
        }
      }
    };
config.content = ["site/pathways.html"];
config.plugins = [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")];
module.exports = config;
